"""Release baseline of the core source hash. Generated by tools/update_core_hash.py; never edit by hand.
Compared by `ness audit` and tests/test_core_hash.py (see ness.integrity)."""

CORE_SOURCE_HASH = "1169a6a8274612b20a11b1c5a811edd4671e11e0dfa186b54d12239aece67a99"
