"""Release baseline of the core source hash. Generated by tools/update_core_hash.py; never edit by hand.
Compared by `ness audit` and tests/test_core_hash.py (see ness.integrity)."""

CORE_SOURCE_HASH = "a0d64f2431088f0dcdd812bcb195295bb8fc0f7bef43ec45390f288b10912ab9"
