"""Core-source integrity: a content hash over the platform package that lets anyone prove the
core was not modified.

``core_source_hash()`` hashes every ``.py`` file under ``ness/`` except the reference plugins
(they are ordinary plugins that happen to ship with the platform), the baseline file itself,
and anything inside a hidden directory (``.ipynb_checkpoints/``, editor and tool caches) or
``__pycache__``: exactly the sources a wheel ships, so an editor autosave in a development tree
can never change the hash (ADR-0016). The baseline recorded at release lives in ``ness/_core_hash.py``; ``ness audit``
compares the two, and ``tests/test_core_hash.py`` fails whenever core changes without the
baseline being regenerated (``python tools/update_core_hash.py``).

Instance implementers never edit core: an instance is a separate package plus configuration
(see docs/AGENT_HANDOFF.md). ``ness audit --strict`` exits non-zero on a mismatch so an
instance's CI can assert it runs on an unmodified platform.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path

EXCLUDED_PARTS = ("__pycache__", "reference_plugins")
BASELINE_FILE = "_core_hash.py"


def core_source_hash(package_dir: Path | None = None) -> str:
    """sha256 over the core package sources (paths + bytes), deterministic across machines."""
    import ness
    root = package_dir or Path(ness.__file__).parent
    h = hashlib.sha256()
    for p in sorted(root.rglob("*.py")):
        rel = p.relative_to(root)
        if any(part in EXCLUDED_PARTS or part.startswith(".") for part in rel.parts[:-1]) or p.name == BASELINE_FILE or p.name.startswith("."):
            continue
        h.update(str(rel).replace("\\", "/").encode())
        h.update(p.read_bytes())
    return h.hexdigest()


def baseline_hash() -> str | None:
    """The hash recorded at release, or None when the package carries no baseline."""
    try:
        from ._core_hash import CORE_SOURCE_HASH
    except ImportError:
        return None
    return CORE_SOURCE_HASH or None


@dataclass(frozen=True)
class IntegrityReport:
    computed: str
    baseline: str | None
    package_dir: str
    editable_install: bool

    @property
    def matches(self) -> bool | None:
        return None if self.baseline is None else self.computed == self.baseline

    def summary(self) -> str:
        if self.baseline is None:
            status = "no baseline recorded in this build (development tree)"
        elif self.matches:
            status = "MATCHES the release baseline: core sources are unmodified"
        else:
            status = "DIFFERS from the release baseline: core sources were modified after release (or this is an unreleased development tree)"
        install = "editable / source checkout" if self.editable_install else "installed package"
        return (f"core source hash {self.computed[:16]}...  baseline {self.baseline[:16] + '...' if self.baseline else '-'}\n"
                f"  {status}\n  package: {self.package_dir} ({install})")


def check_core_integrity() -> IntegrityReport:
    import ness
    pkg = Path(ness.__file__).parent
    editable = pkg.parent.name == "src" and (pkg.parent.parent / "pyproject.toml").exists()
    return IntegrityReport(core_source_hash(pkg), baseline_hash(), str(pkg), editable)


def write_baseline(package_dir: Path | None = None) -> str:
    """Regenerate ``ness/_core_hash.py`` (maintainers, at release or after a core change)."""
    import ness
    root = package_dir or Path(ness.__file__).parent
    digest = core_source_hash(root)
    (root / BASELINE_FILE).write_text(
        '"""Release baseline of the core source hash. Generated by tools/update_core_hash.py; never edit by hand.\n'
        'Compared by `ness audit` and tests/test_core_hash.py (see ness.integrity)."""\n\n'
        f'CORE_SOURCE_HASH = "{digest}"\n')
    return digest
